# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d4f9900d3474f0b793815d18979a489eefb8fb11f2a3a8381f4ecdcd12964319109275285d820b5a1254602b368e524505a8e3628a441ad60a9861467981828

test:
  secret_key_base: c1d251c2f8f339a222e5a402b8ff90a77d0a6e1558f22173ff12601c1c333ca8e62a09e16f77cdbb0e2b0b2a13785b8ee0da8e18edcafb5f086da3dd4355703d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
